version: '3.3'
services:
  postgres_clientes:
    image: postgres:15
    container_name: postgres_clientes
    environment:
      POSTGRES_USER: bruno
      POSTGRES_PASSWORD: root
      POSTGRES_DB: clientesdb
    ports:
      - 5452:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data